#
# Executes commands at login pre-zshrc.
#
# zshenv ➠ ❰zprofile❱ ➠ zshrc ➠ zpreztorc ➠ zlogin ➠ zlogout
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
    typeset -gx BROWSER='open'
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
    typeset -gx EDITOR='nano'
fi
if [[ -z "$VISUAL" ]]; then
    typeset -gx VISUAL='nano'
fi
if [[ -z "$PAGER" ]]; then
    typeset -gx PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
    typeset -gx LANG='en_US.UTF-8'
fi

#
# Paths
# Note: see zprofile.d/90-home.zsh for more additions.
#

# Ensure path arrays are global, and will ignore addition of duplicate entries.
typeset -gU path cdpath fpath mailpath

# Set the list of directories that Zsh searches for executables.
path=(
    /usr/local/{bin,sbin}
    $path
)

# Set the list of directories that `cd` searches (in addition to $PWD).
# cdpath=(
#     $cdpath
# )

# Add paths to directories containing completion data.
# fpath=(
#     $fpath
# )

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
    # typeset -gx LESS='-g -i -M -R -S -w -X -z-4'
    typeset -gx   LESS='-g -i -M -R -S -w    -z-4' # Scrolling enabled
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  typeset -gx LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Process `zprofile.d` Extension Files
#
for profile_file ( ${ZDOTDIR:-$HOME}/.zprezto/runcoms/zprofile.d/*.zsh(Nn) )
{
    [[ -s "${profile_file}" ]] && { source "${profile_file}" }
}
