#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
    export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nano'
export VISUAL='nano'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
    export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays are global, and will ignore addition of duplicate entries.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that `cd` searches (in addition to $PWD).
cdpath=(
    ~
    ~/Projects/Development
    $cdpath
)

# Set the list of directories that zsh searches for executables.
path=(
    ~/Local/{bin,sbin}
    /usr/local/{bin,sbin}    # Homebrew
    /usr/local/opt/ruby/bin  # Homebrew Ruby
    ~/.composer/vendor/bin   # Composer (PHP)
    ~/.mozbuild/git-cinnabar # mozilla
    ~/.cargo/bin             # Rust
    $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
#export LESS='-F -g -i -M -R -S -w -X -z-4'
export  LESS='   -g -i -M -R -S -w    -z-4' # Scrolling enabled

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
    export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Java
#

# Dynamically set JAVA_HOME to the currently selected JVM.
# Fail silently if it's not present.
export JAVA_HOME="$(/usr/libexec/java_home > /dev/null 2>&1; trap)"

#
# Python
#

export PYTHONSTARTUP="${HOME}/.pythonrc"




#
# Load External Profile Extension Files
# THIS SECTION SHOULD BE LAST IN THIS FILE.
#

for zprofile_file in ${ZDOTDIR:-$HOME}/.zprezto/runcoms/zprofile-*(.N); do
    source $zprofile_file
done

